QA_TEST/blueprints/qa.py
from flask import Blueprint,render_template,request,g,redirect,url_for,flash
from decorators import login_required
from .forms import QuestionForm,CommentForm
from models import QuestionModel,AnswerModel
from exts import db
from sqlalchemy import or_
bp = Blueprint("qa",__name__,url_prefix="/")
@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    return render_template("index.html",questions = questions)

#问答详情页面，在详情页面可以根据内容进行评论
@bp.route("/question/<int:id>")
def question_detail(id):
    question = QuestionModel.query.get(id)
    return render_template("detail.html",question=question)

@bp.route("/comment/<int:question_id>",methods=['POST'])
@login_required
def comment(question_id):
    form = CommentForm(request.form)
    if form.validate():
        content = form.content.data
        answer= AnswerModel(content =content,question_id=question_id,author =g.user)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.question_detail",id = question_id))
    else:
        flash("评论内容不能为空！")
        return redirect(url_for("qa.question_detail",id = question_id))



@bp.route("/question/public",methods=['GET','POST'])
@login_required
def public_question():
    #判断是否登录，如果没有登录，就跳转到登录页面
    if request.method == "GET":
        return render_template("public_question.html")
    else:
        form = QuestionForm(request.form)
        #验证成功以后就可以将数据存放到数据库中，这里需要先建立模型
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title,content=content,author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或内容格式错误")
            return redirect(url_for("qa.public_question"))


@bp.route("/search")
def search():
    q = request.args.get("q")
    #filter_by：直接使用的是字段名称
    # filter:使用模型，字段名称
    questions = QuestionModel.query.filter(or_(QuestionModel.title.contains(q),QuestionModel.content.contains(q))).order_by(db.text("-create_time"))
    return render_template("index.html",questions=questions)

QA_TEST/blueprints/user.py
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   url_for,
                   jsonify,
                   session,
                   flash)
from exts import mail,db
from flask_mail import Message
from models import EmailCaptchaModel,UserModel
from datetime import datetime
import string,random
from .forms import RegisterForm,LoginForm
from werkzeug.security import generate_password_hash,check_password_hash
bp = Blueprint("user",__name__,url_prefix="/user")
@bp.route("/login",methods=["GET","POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password,password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱和密码不匹配！")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式错误！")
            return redirect(url_for("user.login"))

@bp.route(("/logout"))
def logout():
    #清除session中的所有数据
    session.clear()
    return redirect(url_for("user.login"))

@bp.route("/register",methods=['GET','POST'])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))

@bp.route("/captcha",methods=['GET','POST'])
def get_captcha():
    #GET POST
    email = request.form.get("email")
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters,4))
    if email:
        message = Message(
        subject="电影问答：注册验证码",
        recipients=[email],
        body=f"【电影问答】您的注册验证码是：{captcha}，请不要告诉任何人。"
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email,captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        print("captcha",captcha)
        #用jsonify来给js代码返回数据
        #code:200,成功的，正常的请求
        return jsonify({"code":200})
    else:
        # code:400,客户端错误
        return jsonify({"code":400,'message':"请先传递邮箱！"})

QA_TEST/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for("static",filename="bootstrap/bootstrap4.6min.css") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="css/init.css") }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">电影问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('qa.public_question')}}">发布问答</a>
                </li>
                <li class="nav-item ml-2">
                    <form class="form-inline my-2 my-lg-0" method="get" action="{{ url_for("qa.search")}}">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search" name="q">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user %}
                <li class="nav-item ">
                    <a class="nav-link" >{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("user.logout") }}">退出登录</a>
                </li>
                {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>
<footer class="footer navbar-fixed-bottom mt-4 bg-dark text-light small" style="position:absolute;right:0;left:0;margin-bottom:0;z-index: 1030">
    <div class="container">
        <div class="row pt-3 pb-5">
            <div class="col-sm-12 col-md-10 p-3">
                <div>电影问答系统</div>
                <div>
                    <ul class="nav">
                        <li class="nav-item">
                          <a class="nav-link text-white" href="#">关于我们</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-white" href="#">联系我们</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-white" href="#">项目实践</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link text-white" href="#">团队信息</a>
                        </li>
                      </ul>
                </div>
                <div class="text-muted">
                    <i>©2021-2022</i> 中国传媒大学舆情实验室 <span class="p-3">版权所有</span> <a class="text-muted" href="#">京ICP备19057319号-1</a>
                </div>
            </div>
            <div class="col-sm-12 col-md-2  p-3">
                <figure class="figure">
                    <img src="{{ url_for('static',filename="images/01.jpg") }}" style="max-height: 100px;height: auto;" class="figure-img rounded" alt="qrcode">
                    <figcaption class="figure-caption">关注我们请扫码</figcaption>
                  </figure>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

QA_TEST/templates/detail.html
{% extends "base.html" %}
{% block title %}评论{% endblock %}
{% block head %}{% endblock %}
{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title text-primary" style="text-align: center">{{ question.title }}</h4>
                    <p class="card-text" style="text-align: center">作者：{{ question.author.username }}
                        发布时间：{{ question.create_time }}</p>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ question.content }}</p>
                    <form action="{{ url_for("qa.comment",question_id=question.id) }}" method="post">
                        <div class="form-group">
                            <label for="exampleInputPassword1"><h5>评论数（{{ question.answers|length }}）</h5></label>
                            <textarea name="content" class="form-control" rows="5" placeholder="发表您的看法"></textarea>
                        </div>
                        {% for message in get_flashed_messages() %}
                            <div class="form-group">
                                <div class="text-danger">{{ message }}</div>
                            </div>
                        {% endfor %}
                        <div class="form-group" style="text-align: right">
                            <button type="submit" class="btn btn-primary">发布评论</button>
                        </div>
                    </form>
                </div>
            </div>
            {% for answer in question.answers %}
                <div class="card mb-2">
                    <div class="row no-gutters">
                        <div class="col-sm-3">
                            <img src="{{ url_for("static",filename="images/0.png") }}" alt="..." class="img-thumbnail"
                                 style="height: 100px;width:50%;">
                            <p class="card-text" style="margin-left: 20px">{{ answer.author.username }}</p>
                            <p class="card-text" style="margin-left: 20px;">{{ answer.create_time }}</p>
                        </div>
                        <div class="col-sm-9">
                            <div class="card-body">
                                <p class="card-text">{{ answer.content }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col"></div>

    </div>


{% endblock %}

QA_TEST/templates/index.html
{% extends "base.html" %}
{% block title %}首页{% endblock %}
{% block head %}
{% endblock %}
{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            {% for question in questions %}
                <div class="card mb-2">
                    <div class="row no-gutters">
                        <div class="col-sm-3">
                            <img src="{{ url_for("static",filename="images/0.png") }}" alt="..." class="img-thumbnail"
                                 style="height: 150px;width:80%;">
                            <p class="card-text" style="margin-left: 20px">{{ question.author.username }}</p>
                            <p class="card-text" style="margin-left: 20px;">{{ question.create_time }}</p>
                            </div>
                        <div class="col-sm-9">
                            <div class="card-body">
                                <h5 class="card-title text-primary"><a href="{{ url_for("qa.question_detail",id = question.id)}}">{{ question.title }}</a></h5>
                                <p class="card-text">{{ question.content }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

QA_TEST/templates/login.html
{% extends "base.html" %}
{% block title %}
    登录
{% endblock %}
{% block head %}{% endblock %}
{% block body %}
    <div class="row mt-4">
        <div class="col-sm"></div>
        <div class="col-sm">
            <form action="{{ url_for("user.login") }}" method="post">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                           name="email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger">{{ message }}</div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                </div>
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
{% endblock %}

QA_TEST/templates/public_question.html
{% extends "base.html" %}
{% block title %}发布问答{% endblock %}
{% block body %}

<div class="row" style="margin-top: 20px">
<div class="col"></div>
<div class="col-10">
    <div class="card text-center">
  <div class="card-header">
    <h3 class="card-title text-primary" style="text-align: center">发布问题</h3>
  </div>
   <form action="{{ url_for("qa.public_question")}}" method="post">
  <div class="card-body">
    <h5 class="card-title"><input type="text" name="title" class="form-control" placeholder="请输入标题"></h5>
    <p class="card-text"><textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea></p>
      <div class="form-group" style="text-align: right">
    <button class="btn btn-primary">发布</button>
      </div>
  </div>
     </form>
  <div class="card-footer text-muted">
    您发布的内容会在首页中出现
  </div>
</div>
</div>
<div class="col"></div>
</div>
{% endblock %}

QA_TEST/templates/register.html
{% extends "base.html" %}
{% block title %}
    注册
{% endblock %}
{% block head %}
    <script src="{{ url_for("static",filename="jquery/jquery-3.6.0.min.js") }}"></script>
    <script src="{{ url_for("static",filename="js/register.js") }}"></script>
{% endblock %}
{% block body %}
    <div class="row mt-4">
        <div class="col-sm"></div>
        <div class="col-sm">
            <form method="POST" action="{{ url_for('user.register')}}">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    <small id="emailHelp" class="form-text text-muted">我们不会对任何人泄露你的邮箱信息</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">用户</label>
                    <input type="text" class="form-control" name="username">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="password_confirm">
                </div>
                <button type="submit" class="btn btn-primary btn-block">立即注册</button>
            </form>
        </div>
        <div class="col-sm"></div>
    </div>
{% endblock %}